baseURL = 'https://shingtaklam1324.github.io/'
languageCode = 'en-gb'
title = 'Shing Tak Lam'
theme = 'typo'

[taxonomies]
tag = 'tags'

# Google analytics code
# googleAnalytics = "G-xxxxxxxxx"

[params]
# Meta description
description = "PhD student in Complex Geometry"

# Appearance settings
theme = 'auto'
colorPalette = 'default'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'Hi!'
homeIntroContent = """
I am a PhD student at the University of Warwick, supervised by [Ruadhaí Dervan](https://www.maths.gla.ac.uk/~rdervan/). My research interests are in complex geometry.

I am a co-organiser of [Warwick Junior Algebraic Geometry](https://warwick.ac.uk/fac/sci/maths/research/events/seminars/areas/jaws/) (with Chunkai and Yaoqi) and of [CALF](https://calfseminar.weebly.com/) (with Sasha and Yijue). Please get in touch if you are interested in giving a talk at either.
"""

# # Collection to display on home
# homeCollectionTitle = 'Posts'
# homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/shing-tak-lam-3237bb1b7/"

# [[params.social]]
# name = "medium"
# url = "https://medium.com/@user"

[[params.social]]
name = "github"
url = "https://github.com/shingtaklam1324"

[[params.social]]
name = "email"
url = "mailto:stl45@cantab.ac.uk"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "writing"
url = "/writing"

# [[params.menu]]
# name = "courses"
# url = "/courses"

# [[params.menu]]
# name = "essay"
# url = "/essay"

[[params.menu]]
name = "talks"
url = "/talks"

[[params.menu]]
name = "travels"
url = "/travels"

[[params.menu]]
name = "teaching"
url = "/teaching"

# [[params.menu]]
# name = "posts"
# url = "/posts"

[[params.menu]]
name = "links"
url = "/links"

[[params.menu]]
name = "about"
url = "/about"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'algol'
[markup.goldmark.renderer]
unsafe = true

# # Giscus comments
# [params.giscus]
# enable = false
# repo = "user/repo"
# repoid = "repoId"
# category = "General"
# categoryid = "categoryId"
# mapping = "pathname"
# theme = "preferred_color_scheme"